### ISSUE TITLE
Doesn't support Ember 2.X

### ISSUE THREAD

**Issue by mattbearman** [piceaTech/ember-rapid-forms#81] opened 2016-01-27 14:10 UTC
When installing on Ember 2.3.0 I got the following error:

File: modules/ember-rapid-forms/templates/components/form-group-control.hbs
Assertion Failed: Using `{{view}}` or any path based on it (L3:C8) has been removed in Ember 2.0

**Comment by GCorbel** [comment] 2016-01-27 14:21
Can you check with the master branch or the v1.0.0-beta4 ? I'm using it on Ember 2 applications and it works. On the [source file](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/templates/components/form-group-control.hbs), you can see it does not use `{{view}}`.

**Comment by mattbearman** [comment] 2016-01-27 14:55
Thanks for the quick response, I've just tried installing the master branch and it's fixed the error, but {{em-input}} isn't rendering a field. I haven't installed or set up ember-validations, is that a requirement?

**Comment by GCorbel** [comment] 2016-01-27 15:01
ember-validations is not a requirement. You have to put it in a `em-form`. This should work : 
    {{#em-form model=model}}
        {{em-input property="name" label="Full Name" placeholder="Enter a name..."}}
        {{em-input property="password" label="Password" placeholder="And password..." type="password" disabled=nameHasValue}}
        {{em-text property="comment" label="Comment" placeholder="Comment please.." rows=4}}
        {{em-select property="gender" label="Gender" prompt="-select-" content=genderOptions optionValuePath="content.id" optionLabelPath="content.name"}}
        {{em-checkbox property="active" label="Active?"}}
    {{/em-form}}

Has show in [the getting started page](http://piceatech.github.io/ember-rapid-forms/#/getstarted).

**Comment by mattbearman** [comment] 2016-01-27 15:05
I've currently got:

    {{#em-form model=model}}
      {{em-input property="email" label="Email Address" placeholder="Email Address"}}
    {{/em-form}}

The model is definitely loaded, and has the property email. I can see in the ember inspector that em-form component is loading the model correctly, but for some reason it's only rendering:

    em-form
      |- em-input
      |    |- form-group
      |- em-form-submit

I'd expect to see an html-input or something under form group.

**Comment by GCorbel** [comment] 2016-01-27 15:09
This is definitively a strange issue... Did `{{model.email}}` returns something (with a value in the email attribute obviously)?

**Comment by mattbearman** [comment] 2016-01-27 15:13
Yeah, if I put `{{model.email}}` in the template it shows the email address fine. 

I installed the truth helpers straight from npm using `ember install ember-truth-helpers`, is there possibly a later version I should install?

**Comment by spruce** [comment] 2016-01-27 15:16
That is really strange. Can You post the versions you are using? (ember, ember-data, maybe package.json?)

**Comment by GCorbel** [comment] 2016-01-27 15:18
Is there something in the inspector? Is there a form tag or something else?

Can you try to use [the input helper](https://guides.emberjs.com/v2.3.0/templates/input-helpers/). This is what `{{em-input}}` do internally.

**Comment by mattbearman** [comment] 2016-01-27 15:20
No problem:

Ember 2.3.0
Data: 2.3.2
Package.json:

    {
      "name": "bm-client-app",
      "version": "0.0.0",
      "description": "Small description for bm-client-app goes here",
      "private": true,
      "directories": {
        "doc": "doc",
        "test": "tests"
      },
      "scripts": {
        "build": "ember build",
        "start": "ember server",
        "test": "ember test"
      },
      "repository": "",
      "engines": {
        "node": ">= 0.10.0"
      },
      "author": "",
      "license": "MIT",
      "devDependencies": {
        "broccoli-asset-rev": "^2.2.0",
        "ember-cli": "1.13.15",
        "ember-cli-app-version": "^1.0.0",
        "ember-cli-babel": "^5.1.5",
        "ember-cli-content-security-policy": "0.4.0",
        "ember-cli-dependency-checker": "^1.1.0",
        "ember-cli-flash": "1.3.8",
        "ember-cli-htmlbars": "^1.0.1",
        "ember-cli-htmlbars-inline-precompile": "^0.3.1",
        "ember-cli-ic-ajax": "0.2.4",
        "ember-cli-inject-live-reload": "^1.3.1",
        "ember-cli-less": "^1.5.3",
        "ember-cli-qunit": "^1.0.4",
        "ember-cli-release": "0.2.8",
        "ember-cli-sri": "^1.2.0",
        "ember-cli-uglify": "^1.2.0",
        "ember-data": "1.13.15",
        "ember-disable-proxy-controllers": "^1.0.1",
        "ember-export-application-global": "^1.0.4",
        "ember-rapid-forms": "git+https://github.com/piceaTech/ember-rapid-forms.git#59e55bdcf0e25b68ba606fc939ecf7831a88d33f",
        "ember-simple-auth": "1.0.1",
        "ember-truth-helpers": "1.2.0"
      }
    }

Inspector just has what I posted before (em-form > em-input > form-group), I'll try the input helper

**Comment by mattbearman** [comment] 2016-01-27 15:23
Using the standard input helper did render a text field correctly, but of course it's missing all the bootstrap goodness

**Comment by GCorbel** [comment] 2016-01-27 15:38
I don't have the time to work on it right now but I'll check tonight. If you want to progress, you can check the behaviour by placing a breakpoint on the ember-rapid-forms module. I have no idea right now.

**Comment by mattbearman** [comment] 2016-01-27 15:40
Thanks for the help so far, I appreciate it's a bit of an edge case. I'll look into it as well and let you know if I figure anything out.

**Comment by GCorbel** [comment] 2016-01-29 13:08
Hi, it works for me we the same dependencies. Can you share your code in a Github repo? I have no idea for now.

**Comment by GCorbel** [comment] 2016-02-06 14:29
I will close this is use because I'm not able to reproduce it. Feel free to reopen it.

**Closed by GCorbel** 2016-02-06 14:29 UTC
